### ISSUE TITLE
optiong for keeping existing change/ creation dates of files

### ISSUE THREAD

**Issue by BenBruser** [llimllib/obsidian-guid-plugin#3]
I tried the plugin and it would be great, if the original date would be kept in the .md-files.

All of my files now were changed to the current date, which looks strange in the calendar.

Thanks,
Ben

**Comment by llimllib** [comment]
I think it's pretty fundamental that adding something to the front matter of a note causes the note to be updated - I don't think it's possible or desirable to update the file but not have the file's date get updated.

Also it's only a one-time deal; in the future your notes will get updated immediately.

I'm open to ideas, but unless somebody has a more specific idea for how this problem could be solved, I'm going to close the issue
